/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
public class Issue extends javax.swing.JFrame {

    /**
     * Creates new form Issue
     */
    public Issue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Bid = new javax.swing.JTextField();
        Sid = new javax.swing.JTextField();
        ID = new com.toedter.calendar.JDateChooser();
        DD = new com.toedter.calendar.JDateChooser();
        Ok = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Book ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 106, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Student ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 158, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Issue Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 207, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Due Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 254, -1, -1));

        Bid.setBackground(new java.awt.Color(255, 255, 204));
        Bid.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(Bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 104, 201, -1));

        Sid.setBackground(new java.awt.Color(255, 255, 204));
        Sid.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(Sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 158, 201, -1));

        ID.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 207, 201, -1));

        DD.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(DD, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 254, 201, -1));

        Ok.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ok.setText("Issue");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });
        getContentPane().add(Ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 337, 89, 33));

        Close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 337, 89, 33));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/l1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
       new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_CloseActionPerformed

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dFormat= new SimpleDateFormat("dd-MM-yyyy");
         String bookID=Bid.getText();
        String SID=Sid.getText();
        String Issue=dFormat.format(ID.getDate());
         String Due=dFormat.format(DD.getDate());
         String RbStatus="No";
         try{
             Connection con=javaconnect.connectdb();
            Statement st=con.createStatement();
             con.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
            ResultSet rs=st.executeQuery("Select * from Book where bookID='"+bookID+"'");
            if(rs.next())
            {
                ResultSet rs1=st.executeQuery("Select * from Student where studentID='"+SID+"'");
                if(rs1.next())
                {
                    st.executeUpdate("insert into IssueB values('"+bookID+"','"+SID+"','"+Issue+"','"+Due+"','"+RbStatus+"')");
                     JOptionPane.showMessageDialog(null,"Book Successfully Issued");
                     setVisible(false);
                     new Issue().setVisible(true);
                }
                else
                    JOptionPane.showMessageDialog(null,"Incorrect Student Id");
            }
            else
                JOptionPane.showMessageDialog(null,"Incorrect Book Id");
         }
         catch(Exception e)
         {
         JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            setVisible(false);
            new Issue().setVisible(true);
         }
    }//GEN-LAST:event_OkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bid;
    private javax.swing.JButton Close;
    private com.toedter.calendar.JDateChooser DD;
    private com.toedter.calendar.JDateChooser ID;
    private javax.swing.JButton Ok;
    private javax.swing.JTextField Sid;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
